apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/auth/
  - ./dev-auth-configmap.yaml
patches:
  - path: ./dev-auth-patch-deploy.yaml
  - path: ./dev-auth-patch-service.yaml
images:
  - name: auth-image
    newName: 615677714887.dkr.ecr.eu-central-1.amazonaws.com/ardanlabs-auth
    newTag: latest
