apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/sales/
  - ./dev-sales-configmap.yaml
patches:
  - path: ./dev-sales-patch-deploy.yaml
  - path: ./dev-sales-patch-service.yaml
images:
  - name: sales-image
    newName: 615677714887.dkr.ecr.eu-central-1.amazonaws.com/ardanlabs-sales
    newTag: 0.0.1
  - name: metrics-image
    newName: 615677714887.dkr.ecr.eu-central-1.amazonaws.com/ardanlabs-metrics
    newTag: 0.0.1
