apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-05c6e9a29e95623d2
  directoryPerms: "777"
  gid: "1000"
  uid: "1000"